#!/usr/bin/env python3
"""Continuous burn-down coordinator for backlog and remediation work.

The coordinator does four things in a repeatable loop:
1. Refresh local backlog sources and optional GitHub issue state
2. Run deterministic validators and convert failures into explicit todos
3. Separate actionable work from real blockers
4. Optionally claim the next GitHub issue for a runtime

This is designed as a bounded, testable loop rather than an unbounded daemon.
Use ``--max-iterations`` with ``--interval-seconds`` if you want it to keep
refreshing until queues are clear or blocked.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    import orjson
except ModuleNotFoundError:  # pragma: no cover - fallback for minimal envs

    class _OrjsonCompat:
        """Compatibility wrapper for environments without orjson."""

        @staticmethod
        def loads(data: str | bytes) -> Any:
            if isinstance(data, bytes):
                data = data.decode()
            return json.loads(data)

        @staticmethod
        def dumps(data: Any, option: int | None = None) -> bytes:
            del option
            return json.dumps(data, indent=2, separators=(",", ": ")).encode()

        OPT_INDENT_2 = 0

    orjson = _OrjsonCompat()

try:
    from scripts.backlog_groomer import BacklogGroomer
    from scripts.ci_health_monitor import CIHealthMonitor
    from scripts.github_issue_claim import GitHubIssueClaimer
    from scripts.migrate_backlog_to_github import BacklogParser
    from scripts.sprint_validator import SprintValidator
    from scripts.validate_documentation_accuracy import DocumentationValidator
except ModuleNotFoundError:  # pragma: no cover - direct script execution fallback
    from backlog_groomer import BacklogGroomer
    from ci_health_monitor import CIHealthMonitor
    from github_issue_claim import GitHubIssueClaimer
    from migrate_backlog_to_github import BacklogParser
    from sprint_validator import SprintValidator
    from validate_documentation_accuracy import DocumentationValidator
from schemas.validate_schemas import validate_json_file

DEFAULT_REPORT = "logs/continuous_burndown_report.json"


@dataclass(frozen=True)
class TodoItem:
    """Normalized work item generated by the coordinator."""

    id: str
    title: str
    source: str
    priority: str
    status: str
    recommended_runtime: str
    blocked: bool
    details: str


def _utc_now() -> str:
    """Return the current UTC timestamp."""
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def _load_json(path: Path, default: Any) -> Any:
    """Load JSON from disk with a fallback default."""
    if not path.exists():
        return default

    with open(path, "rb") as handle:
        return orjson.loads(handle.read())


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    """Persist JSON payload to disk."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(orjson.dumps(payload, option=getattr(orjson, "OPT_INDENT_2", 0)))


def _priority_sort_key(priority: str) -> int:
    """Map priority labels to sort order."""
    order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    return order.get(priority, 9)


def _runtime_for_item(source: str, blocked: bool, title: str, details: str) -> str:
    """Recommend the safest runtime for a work item."""
    text = f"{title} {details}".lower()
    if blocked:
        return "human"
    if source in {"escalations", "ci_health"}:
        return (
            "human"
            if "decision" in text or "stop all sprint work" in text
            else "claude"
        )
    if "new file" in text or "create file" in text:
        return "copilot"
    if source in {"validators", "sprint_tracker", "task_queue", "github"}:
        return "claude"
    return "codex"


class ContinuousBurndownCoordinator:
    """Refresh backlog sources, run validators, and emit normalized todos."""

    def __init__(self, repo_root: Path, runtime: str = "codex"):
        self.repo_root = repo_root
        self.runtime = runtime
        self.state_dir = self.repo_root / "data" / "skills_state"
        self.sprint_tracker_path = self.state_dir / "sprint_tracker.json"
        self.backlog_path = self.state_dir / "backlog.json"
        self.task_queue_path = self.state_dir / "task_queue.json"
        self.escalations_path = self.state_dir / "escalations.json"
        self.markdown_backlog_path = self.repo_root / ".github" / "BACKLOG.md"
        self.remediation_queue_candidates = [
            self.repo_root / "content-remediation-queue.json",
            self.repo_root / "queue.json",
            self.repo_root / "logs" / "content-remediation-queue.json",
        ]

    def collect_sprint_todos(self) -> list[TodoItem]:
        """Collect incomplete current-sprint stories."""
        tracker = _load_json(self.sprint_tracker_path, {})
        current_sprint = tracker.get("current_sprint")
        if not current_sprint:
            return []

        sprint_key = f"sprint_{current_sprint}"
        sprint = tracker.get("sprints", {}).get(sprint_key, {})
        todos: list[TodoItem] = []

        for story in sprint.get("stories", []):
            status = str(story.get("status", "unknown"))
            if status == "complete":
                continue

            story_id = story.get("id", "unknown")
            title = str(story.get("name", story.get("title", f"Story {story_id}")))
            priority = str(story.get("priority", "P2"))
            blocked = status == "blocked"
            details = str(story.get("notes", story.get("description", "")))
            todos.append(
                TodoItem(
                    id=f"sprint-{current_sprint}-story-{story_id}",
                    title=title,
                    source="sprint_tracker",
                    priority=priority,
                    status=status,
                    recommended_runtime=_runtime_for_item(
                        "sprint_tracker", blocked, title, details
                    ),
                    blocked=blocked,
                    details=details,
                )
            )

        return todos

    def collect_backlog_todos(self) -> list[TodoItem]:
        """Collect open backlog stories from backlog.json."""
        backlog = _load_json(self.backlog_path, {"stories": []})
        todos: list[TodoItem] = []

        for story in backlog.get("stories", []):
            status = str(story.get("status", "backlog"))
            if status == "complete":
                continue

            title = (
                str(story.get("id", "STORY"))
                + ": "
                + str(story.get("request", story.get("user_story", "Backlog story")))
            )
            priority = str(story.get("priority", "P2"))
            blocked = status == "blocked" or bool(story.get("escalations"))
            details = str(story.get("implementation_notes", ""))
            todos.append(
                TodoItem(
                    id=str(story.get("id", title)),
                    title=title,
                    source="backlog",
                    priority=priority,
                    status=status,
                    recommended_runtime=_runtime_for_item(
                        "backlog", blocked, title, details
                    ),
                    blocked=blocked,
                    details=details,
                )
            )

        return todos

    def collect_markdown_backlog_todos(self) -> list[TodoItem]:
        """Collect open markdown backlog items from .github/BACKLOG.md."""
        if not self.markdown_backlog_path.exists():
            return []

        parser = BacklogParser(str(self.markdown_backlog_path))
        todos: list[TodoItem] = []
        for index, item in enumerate(parser.parse(), start=1):
            status = str(item.get("status", "ready")).lower()
            if status == "complete":
                continue

            title = str(item.get("title", f"Backlog item {index}"))
            details = str(item.get("body", ""))
            blocked = status == "blocked"
            priority = str(item.get("priority", "P2"))
            todos.append(
                TodoItem(
                    id=f"md-backlog-{index}",
                    title=title,
                    source="markdown_backlog",
                    priority=priority,
                    status=status,
                    recommended_runtime=_runtime_for_item(
                        "markdown_backlog", blocked, title, details
                    ),
                    blocked=blocked,
                    details=details,
                )
            )

        return todos

    def collect_task_queue_todos(self) -> list[TodoItem]:
        """Collect open task queue items."""
        queue = _load_json(self.task_queue_path, {"tasks": []})
        todos: list[TodoItem] = []

        for task in queue.get("tasks", []):
            status = str(task.get("status", "pending"))
            if status == "complete":
                continue

            title = str(task.get("title", task.get("task_id", "Queued task")))
            details = ", ".join(task.get("acceptance_criteria", []))
            blocked = status == "blocked"
            priority = str(task.get("priority", "P2"))
            todos.append(
                TodoItem(
                    id=str(task.get("task_id", title)),
                    title=title,
                    source="task_queue",
                    priority=priority,
                    status=status,
                    recommended_runtime=_runtime_for_item(
                        "task_queue", blocked, title, details
                    ),
                    blocked=blocked,
                    details=details,
                )
            )

        return todos

    def collect_escalation_blockers(self) -> list[TodoItem]:
        """Collect pending human escalations."""
        escalations = _load_json(self.escalations_path, {"pending_escalations": []})
        todos: list[TodoItem] = []

        for escalation in escalations.get("pending_escalations", []):
            if escalation.get("resolved"):
                continue

            title = str(escalation.get("question", "Human decision required"))
            recommendation = str(escalation.get("recommendation", ""))
            todos.append(
                TodoItem(
                    id=str(escalation.get("escalation_id", title)),
                    title=title,
                    source="escalations",
                    priority=str(escalation.get("priority", "P1")),
                    status="blocked",
                    recommended_runtime="human",
                    blocked=True,
                    details=recommendation,
                )
            )

        return todos

    def collect_validator_todos(self) -> list[TodoItem]:
        """Run deterministic validators and convert findings into todos."""
        todos: list[TodoItem] = []

        sprint_validator = SprintValidator(str(self.repo_root / "SPRINT.md"))
        active_sprint = sprint_validator.get_active_sprint()
        if not active_sprint:
            todos.append(
                TodoItem(
                    id="validator-no-active-sprint",
                    title="Define an active sprint before continuing work",
                    source="validators",
                    priority="P0",
                    status="blocked",
                    recommended_runtime="human",
                    blocked=True,
                    details="SPRINT.md does not expose an active sprint header.",
                )
            )

        doc_validator = DocumentationValidator(repo_root=self.repo_root)
        doc_validator.validate_all()
        for index, error in enumerate(doc_validator.errors, start=1):
            todos.append(
                TodoItem(
                    id=f"docs-error-{index}",
                    title="Documentation accuracy remediation",
                    source="validators",
                    priority="P1",
                    status="pending",
                    recommended_runtime="claude",
                    blocked=False,
                    details=error,
                )
            )
        for index, warning in enumerate(doc_validator.warnings, start=1):
            todos.append(
                TodoItem(
                    id=f"docs-warning-{index}",
                    title="Documentation drift follow-up",
                    source="validators",
                    priority="P2",
                    status="pending",
                    recommended_runtime="codex",
                    blocked=False,
                    details=warning,
                )
            )

        groomer = BacklogGroomer(str(self.sprint_tracker_path))
        groomer.generate_report()
        for category, issues in groomer.issues.items():
            for index, issue in enumerate(issues, start=1):
                issue_priority = (
                    "P1" if category in {"undefined", "priority_drift"} else "P2"
                )
                details = issue.get("recommendation", "")
                title = f"Backlog {category.replace('_', ' ')} remediation"
                todos.append(
                    TodoItem(
                        id=f"backlog-{category}-{index}",
                        title=title,
                        source="validators",
                        priority=issue_priority,
                        status="pending",
                        recommended_runtime="claude",
                        blocked=False,
                        details=str(details),
                    )
                )

        ci_health = CIHealthMonitor()
        ci_result = ci_health.check_health(last_n=3)
        ci_status = str(ci_result.get("status", "UNKNOWN"))
        if ci_status == "RED":
            todos.append(
                TodoItem(
                    id="ci-red-build",
                    title="CI is red and blocks sprint execution",
                    source="ci_health",
                    priority="P0",
                    status="blocked",
                    recommended_runtime="human",
                    blocked=True,
                    details=str(ci_result.get("message", "CI failure detected")),
                )
            )
        elif ci_status == "YELLOW":
            todos.append(
                TodoItem(
                    id="ci-monitoring",
                    title="Review CI health before claiming more work",
                    source="ci_health",
                    priority="P2",
                    status="pending",
                    recommended_runtime="claude",
                    blocked=False,
                    details=str(ci_result.get("message", "CI requires monitoring")),
                )
            )

        schema_checks = [
            (
                self.repo_root / "content_queue.json",
                self.repo_root / "schemas" / "content_queue_schema.json",
                "content queue schema validation",
            ),
            (
                self.repo_root / "board_decision.json",
                self.repo_root / "schemas" / "board_decision_schema.json",
                "board decision schema validation",
            ),
        ]
        for json_path, schema_path, title in schema_checks:
            if not json_path.exists() or not schema_path.exists():
                continue
            is_valid, errors = validate_json_file(json_path, schema_path)
            if is_valid:
                continue
            for index, error in enumerate(errors, start=1):
                todos.append(
                    TodoItem(
                        id=f"schema-{json_path.stem}-{index}",
                        title=title,
                        source="validators",
                        priority="P1",
                        status="pending",
                        recommended_runtime="claude",
                        blocked=False,
                        details=error,
                    )
                )

        return todos

    def collect_remediation_queue_todos(self) -> list[TodoItem]:
        """Collect local remediation queue items when present."""
        queue_path = next(
            (
                candidate
                for candidate in self.remediation_queue_candidates
                if candidate.exists()
            ),
            None,
        )
        if queue_path is None:
            return []

        payload = _load_json(queue_path, {"queue": []})
        queue = payload.get("queue", [])
        threshold = payload.get("threshold", 75)
        todos: list[TodoItem] = []

        for index, item in enumerate(queue, start=1):
            score = item.get("currentScore", 100)
            if score >= threshold:
                continue
            post_file = str(item.get("post_file", item.get("file", f"post-{index}")))
            title = str(item.get("title", post_file))
            actions = item.get("actionPlan", item.get("actions", []))
            if isinstance(actions, list):
                details = ", ".join(
                    action.get("action", str(action))
                    if isinstance(action, dict)
                    else str(action)
                    for action in actions[:3]
                )
            else:
                details = str(actions)
            todos.append(
                TodoItem(
                    id=f"remediation-{index}",
                    title=f"Remediate {title}",
                    source="remediation_queue",
                    priority="P1",
                    status="pending",
                    recommended_runtime=_runtime_for_item(
                        "remediation_queue", False, title, details
                    ),
                    blocked=False,
                    details=f"{post_file} score={score} threshold={threshold}; {details}",
                )
            )
        return todos

    def collect_github_todos(self, claim_next: bool = False) -> list[TodoItem]:
        """Collect GitHub issue state and optionally claim the next issue."""
        todos: list[TodoItem] = []
        claimer = GitHubIssueClaimer()

        try:
            next_issue = claimer.find_next_claimable_issue(
                ["enhancement", "quality"], self.runtime
            )
        except RuntimeError as exc:
            todos.append(
                TodoItem(
                    id="github-access-error",
                    title="GitHub access unavailable for issue refresh",
                    source="github",
                    priority="P1",
                    status="blocked",
                    recommended_runtime="human",
                    blocked=True,
                    details=str(exc),
                )
            )
            return todos

        if next_issue is None:
            return todos

        status = "claimed" if claim_next else "pending"
        details = f"Next claimable issue is #{next_issue}"
        if claim_next:
            claim = claimer.claim_issue(next_issue, runtime=self.runtime)
            expiry = claim.expires_at.isoformat() if claim.expires_at else "unknown"
            details = f"Issue #{next_issue} claimed for {self.runtime} until {expiry}"

        todos.append(
            TodoItem(
                id=f"github-issue-{next_issue}",
                title=f"GitHub issue #{next_issue} ready for execution",
                source="github",
                priority="P1",
                status=status,
                recommended_runtime=self.runtime,
                blocked=False,
                details=details,
            )
        )
        return todos

    def collect_once(
        self, include_github: bool = False, claim_next: bool = False
    ) -> dict[str, Any]:
        """Run one refresh pass and return a normalized report."""
        todos = []
        todos.extend(self.collect_sprint_todos())
        todos.extend(self.collect_backlog_todos())
        todos.extend(self.collect_markdown_backlog_todos())
        todos.extend(self.collect_task_queue_todos())
        todos.extend(self.collect_escalation_blockers())
        todos.extend(self.collect_remediation_queue_todos())
        todos.extend(self.collect_validator_todos())
        if include_github:
            todos.extend(self.collect_github_todos(claim_next=claim_next))

        todos_sorted = sorted(
            todos,
            key=lambda item: (item.blocked, _priority_sort_key(item.priority), item.id),
        )
        actionable = [item for item in todos_sorted if not item.blocked]
        blockers = [item for item in todos_sorted if item.blocked]

        return {
            "generated_at": _utc_now(),
            "runtime": self.runtime,
            "actionable_count": len(actionable),
            "blocker_count": len(blockers),
            "empty": len(todos_sorted) == 0,
            "actionable": [asdict(item) for item in actionable],
            "blockers": [asdict(item) for item in blockers],
        }


def _has_remaining_work(report: dict[str, Any]) -> bool:
    """Return True when any actionable work remains."""
    return bool(report.get("actionable"))


def _has_only_blockers(report: dict[str, Any]) -> bool:
    """Return True when there are blockers and no actionable todos."""
    return bool(report.get("blockers")) and not bool(report.get("actionable"))


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Continuous burn-down coordinator")
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root containing data/skills_state and scripts/",
    )
    parser.add_argument(
        "--runtime",
        default=os.environ.get("AGENT_RUNTIME", "codex"),
        help="Runtime name for ownership and GitHub issue claiming",
    )
    parser.add_argument(
        "--include-github",
        action="store_true",
        help="Refresh GitHub issue state via gh",
    )
    parser.add_argument(
        "--claim-next",
        action="store_true",
        help="Claim the next available GitHub issue for this runtime",
    )
    parser.add_argument(
        "--interval-seconds",
        type=int,
        default=0,
        help="Sleep interval between iterations; 0 means run once",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=1,
        help="Maximum refresh passes to execute",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_REPORT,
        help="Path to write the JSON report",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    coordinator = ContinuousBurndownCoordinator(
        repo_root=repo_root, runtime=args.runtime
    )
    output_path = repo_root / args.output

    final_report: dict[str, Any] = {}
    for iteration in range(1, max(args.max_iterations, 1) + 1):
        report = coordinator.collect_once(
            include_github=args.include_github,
            claim_next=args.claim_next and iteration == 1,
        )
        report["iteration"] = iteration
        final_report = report
        _write_json(output_path, report)

        if report["empty"] or _has_only_blockers(report):
            break

        if args.interval_seconds <= 0 or iteration >= args.max_iterations:
            break
        time.sleep(args.interval_seconds)

    print(
        f"Burn-down report: actionable={final_report.get('actionable_count', 0)} "
        f"blockers={final_report.get('blocker_count', 0)} output={output_path}"
    )

    if _has_only_blockers(final_report):
        return 2
    if _has_remaining_work(final_report):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
