#!/usr/bin/env python3
"""Render the B-040 calibration cases into one owner spot-check sheet.

B-040 Phase 2 is not a code gate. The calibration negatives were drafted by an
agent for a judge of its own model family, and the spec's answer to that is the
owner reading a sample — an agent checking its own negatives is precisely the
control the design rules out. This script does not perform that check; it only
removes the cost of performing it, by collapsing 23 YAML files into one ordered
document with the passage, the labelled verdict and the stated reasoning side by
side.

Deterministic and keyless: no judge runs, nothing is scored, no network.

Usage:
    python -m scripts.render_calibration_review_sheet \
        --cases docs/evals/review-gate/cases \
        --out docs/evals/review-gate/SPOT-CHECK.md
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

REQUIRED_FIELDS = ("id", "gate", "expected", "source", "passage", "why")

#: `expected: pass` means "the gate should NOT flag this passage" — a negative.
NEGATIVE = "pass"


def load_cases(cases_dir: Path) -> list[dict[str, Any]]:
    """Load every calibration case, ordered by id.

    Args:
        cases_dir: Directory holding one YAML file per case.

    Returns:
        Cases sorted by ``id`` so the rendered sheet is stable across runs.

    Raises:
        ValueError: If the directory holds no cases, or a case is missing a
            required field. A malformed case is louder than a dropped one —
            silently skipping it would understate the set the owner is checking.

    """
    paths = sorted(cases_dir.glob("*.yaml"))
    if not paths:
        raise ValueError(f"no case files in {cases_dir}")

    cases: list[dict[str, Any]] = []
    for path in paths:
        case = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for field in REQUIRED_FIELDS:
            if field not in case:
                raise ValueError(f"{path.name} is missing required field: {field}")
        cases.append(case)

    return sorted(cases, key=lambda c: str(c["id"]))


def _render_case(case: dict[str, Any], index: int) -> list[str]:
    """Render one case as a numbered block with an agree/disagree control."""
    return [
        f"### {index}. `{case['id']}`",
        "",
        f"**Gate {case['gate']}** · labelled **{case['expected']}** · "
        f"source: `{case['source']}`",
        "",
        "> " + str(case["passage"]).strip().replace("\n", "\n> "),
        "",
        f"**Why it is labelled `{case['expected']}`:** {str(case['why']).strip()}",
        "",
        "- [ ] agree",
        "- [ ] disagree — because:",
        "",
    ]


def render_sheet(cases: list[dict[str, Any]]) -> str:
    """Render the spot-check sheet, negatives first.

    Args:
        cases: Cases as returned by :func:`load_cases`.

    Returns:
        Markdown for the whole sheet. Counts in the header are computed from
        ``cases`` rather than restated from the PR description, so the sheet
        cannot drift from the set it describes.

    """
    negatives = [c for c in cases if c["expected"] == NEGATIVE]
    positives = [c for c in cases if c["expected"] != NEGATIVE]
    sources = {c["source"] for c in cases}
    pct = round(100 * len(negatives) / len(cases)) if cases else 0

    lines = [
        "# Review-gate calibration — owner spot-check",
        "",
        f"**{len(cases)} cases · {len(negatives)} negatives ({pct}%) · "
        f"{len(sources)} source articles**",
        "",
        "Generated by `scripts/render_calibration_review_sheet.py`. Do not edit by "
        "hand — edit the YAML in `docs/evals/review-gate/cases/` and re-render.",
        "",
        "## Why you are reading this",
        "",
        "B-040 Phase 2 is a gate no agent can clear for you: these cases were "
        "drafted by an agent to calibrate a judge of its own model family, so the "
        "set needs a control outside that loop. Tick `agree` where the labelled "
        "verdict is right, `disagree` where it is not. A disagreement is a finding, "
        "not a failure — a mislabelled ground-truth case is worse than a missing "
        "one (README rule 3).",
        "",
        "**Negatives are listed first** because they are the half an agent is most "
        "likely to have got wrong: a positive is drawn from a recorded defect, "
        "whereas a negative asserts that nothing is wrong, which is the harder "
        "claim to check.",
        "",
        f"## Negatives — the gate should NOT flag these ({len(negatives)})",
        "",
    ]
    for i, case in enumerate(negatives, start=1):
        lines.extend(_render_case(case, i))

    lines.extend([f"## Positives — the gate SHOULD flag these ({len(positives)})", ""])
    for i, case in enumerate(positives, start=1):
        lines.extend(_render_case(case, i))

    return "\n".join(lines)


def main() -> int:
    """Render the sheet to disk.

    Returns:
        Process exit code.

    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cases",
        type=Path,
        default=Path("docs/evals/review-gate/cases"),
        help="Directory of calibration case YAML files.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("docs/evals/review-gate/SPOT-CHECK.md"),
        help="Where to write the rendered sheet.",
    )
    args = parser.parse_args()

    cases = load_cases(args.cases)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_sheet(cases) + "\n", encoding="utf-8")
    logger.info("wrote %s (%d cases)", args.out, len(cases))
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    raise SystemExit(main())
